### ISSUE TITLE
How do I rename the resulting output program?

### ISSUE THREAD

**Issue by zai1208** [pgvalle/OpenGLCppTemplate#1]
Exactly what the title says. I want something else instead of exampleProgram. How do I do that?

**Comment by pgvalle** [comment]
Hello, mate! Ty this is my very first issue response. I'm happy!
You see the CMakeLists.txt file? At line 4 you have the following:
`set (FINAL_TARGET exampleProgram)`
You just gotta change exampleProgram.
Again, I thank you for interacting with me. Please if you find anything strange, give me feedback! May God bless you!
Sorry for the late response as well...

**Comment by zai1208** [comment]
I should be thanking you, this is the only properly configured OpenGL template I have found that actually work on MacOS, and contains all the libraries required for [learnOpenGL.com](learnopengl.com)

**Comment by pgvalle** [comment]
Bruh I thank YOU. LOL I don't even have enough lifespan to save money to buy a mac and yet my template for some reason works on it. You tested it. Thank you!
God bless you!
